# Generated by Django 4.0 on 2022-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dml_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
